# Configuration for FreeBayes Snakemake pipeline on CSC Puhti

path_to_reference: Frufa_DTOL.ref_genome.unmasked.mtDNA.fa # mtDNA version
samples_folder: 2_mapping
output_folder: results_mtDNA_310725
chunks_per_chrom: 5

bam_list: bam_mtDNA_min.list

freebayes_path: /projappl/project_2007833/freebayes_v1.3.10

chroms:
  - mtDNA

samples: # Full version
  - H_120_k.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_121_a.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_121_b.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_121_c.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_122_a.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_122_b.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_122_d.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_122_f.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_122_g.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_122_h.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_a.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_b.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_c.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_d.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_e.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_f.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_g.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_h.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_i.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_k.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA