# Configuration for FreeBayes Snakemake pipeline on CSC Puhti

path_to_reference: Frufa_DTOL.ref_genome.unmasked.mtDNA.fa # mtDNA version
samples_folder: 2_mapping
output_folder: results_mtDNA_310725
chunks_per_chrom: 2

bam_list: bam_mtDNA_min.list

chroms:
  - chromosome_2
  - chromosome_3
  - chromosome_1
  - chromosome_4
  - chromosome_5
  - chromosome_10
  - chromosome_7
  - chromosome_8
  - chromosome_13
  - chromosome_25
  - chromosome_16
  - chromosome_6
  - chromosome_15
  - chromosome_11
  - chromosome_17
  - chromosome_9
  - chromosome_12
  - chromosome_21
  - chromosome_26
  - chromosome_20
  - chromosome_14
  - chromosome_18
  - chromosome_27
  - chromosome_19
  - chromosome_24
  - chromosome_22
  - mtDNA

samples: # Full version
  - H_120_k.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_121_a.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_121_b.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_121_c.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_122_a.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_122_b.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_122_d.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_122_f.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_122_g.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_122_h.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_a.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_b.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_c.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_d.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_e.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_f.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_g.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_h.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_i.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA
  - H_13_k.vs.Frufa_DTOL.ref_genome.unmasked.MD.mtDNA