# Configuration for FreeBayes Snakemake pipeline on CSC Puhti

path_to_reference: Frufa_DTOL.ref_genome.unmasked.fa # Full version
samples_folder: 2_mapping
output_folder: results_full_310725
chunks_per_chrom: 20
bam_list: bam.list

freebayes_path: /projappl/project_2007833/freebayes_v1.3.10

chroms:
  - chromosome_2
  - chromosome_3
  - chromosome_1
  - chromosome_4
  - chromosome_5
  - chromosome_10
  - chromosome_7
  - chromosome_8
  - chromosome_13
  - chromosome_25
  - chromosome_16
  - chromosome_6
  - chromosome_15
  - chromosome_11
  - chromosome_17
  - chromosome_9
  - chromosome_12
  - chromosome_21
  - chromosome_26
  - chromosome_20
  - chromosome_14
  - chromosome_18
  - chromosome_27
  - chromosome_19
  - chromosome_24
  - chromosome_22
  - mtDNA

samples: # Full version
  - H_120_k.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_121_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_121_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_121_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_122_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_122_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_122_d.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_122_f.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_122_g.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_122_h.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_13_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_13_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_13_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_13_d.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_13_e.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_13_f.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_13_g.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_13_h.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_13_i.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_13_k.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_131_f.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_131_g.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_131_k.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_133_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_133_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_133_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_133_d.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_159_e.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_159_g.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_159_h.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_159_j.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_159_k.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_160_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_160_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_160_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_160_d.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_160_e.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_195_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_195_d.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_195_k.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_22_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_22_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_22_k.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_23_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_23_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_23_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_24_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_24_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_24_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_24_d.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_251_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_251_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_251_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_251_d.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_251_e.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_251_f.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_251_g.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_251_h.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_251_j.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_251_k.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_267_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_267_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_267_k.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_268_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_268_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_268_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_268_d.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_269_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_269_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_269_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_29_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_29_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_29_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_29_d.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_29_e.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_30_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_30_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_30_d.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_30_f.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_30_k.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_338_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_338_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_338_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_338_d.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_338_k.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_405_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_405_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_405_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_405_d.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_406_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_406_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_406_k.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_407_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_407_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_407_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_41_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_41_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_41_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_42_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_42_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_42_k.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_43_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_43_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_43_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_43_d.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_44_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_44_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_44_d.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_44_e.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_44_f.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_44_g.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_44_h.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_44_i.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_44_j.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_44_k.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_63_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_63_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_63_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_63_k.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_64_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_64_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_65_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_65_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_65_d.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_74_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_74_d.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_74_e.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_74_f.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_74_k.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_75_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_75_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_75_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_75_d.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_75_e.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_84_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_84_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_84_k.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_85_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_85_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_85_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_90_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_90_k.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_91_a.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_91_b.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - H_91_c.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Frufa.12.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Frufa.16.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Frufa.26.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Frufa.37.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Frufa.72.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Frufa.102.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Fprat.2.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Fprat.3.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Fprat.6.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Fprat.117.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Fprat.120.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Fprat.122.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Fprat.123.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Fpol.CBCH1.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Fpol.CBCH2.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Fpol.CBCH3.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Flug.11.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Flug.56.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Flug.88.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Flug.108.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Flug.113.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Flug.115.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Flug.124.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Faqu.70.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Faqu.67.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Faqu.103.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Faqu.107.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Fpol.NAZa.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Fpol.CAGa.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Fpol.VDa.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Flug.1.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Faqu.CBAQ2.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Faqu.Lai.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Faqu.Loa.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Faqu.30.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Faqu.31.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Faqu.22.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Faqu.109.vs.Frufa_DTOL.ref_genome.unmasked.MD
  - Faqu.CBAQ1.vs.Frufa_DTOL.ref_genome.unmasked.MD